# Ścieżka do dokumentacji w formacie JSON
app.swagger:
    path: /api/docs.json
    methods: GET
    defaults:
        _controller: nelmio_api_doc.controller.swagger

# Interfejs graficzny (Swagger UI)
app.swagger_ui:
    path: /api/docs
    methods: GET
    defaults:
        _controller: nelmio_api_doc.controller.swagger_ui
